# Generated by Django 3.2 on 2022-05-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_rename_menu_ordermenu_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderMenu',
            new_name='Menu',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordermenu',
            new_name='menu',
        ),
    ]
