# Generated by Django 3.2 on 2022-06-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_menu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='postcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
