# Generated by Django 3.2 on 2022-06-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20220629_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='postcode',
            new_name='eircode',
        ),
    ]
