# Generated by Django 3.2 on 2022-07-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
