# Generated by Django 3.2 on 2022-07-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_alter_ordermodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
    ]
