# Generated by Django 3.2 on 2022-07-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_remove_ordermodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='items',
        ),
    ]
