# Generated by Django 3.2 on 2022-07-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_auto_20220704_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.ManyToManyField(
                choices=[('Meals', 'Meals'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')],
                related_name='item',
                to='delivery.Category'
            ),
        ),
    ]
