# Generated by Django 3.2 on 2022-07-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_order_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='eircode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
