# Generated by Django 3.2 on 2022-07-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0026_auto_20220704_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='eircode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
