# Generated by Django 3.2 on 2022-07-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0028_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
