# Generated by Django 3.2 on 2022-07-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0033_alter_ordermodel_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
