# Generated by Django 3.2 on 2022-07-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0034_alter_ordermodel_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='transaction_id',
        ),
    ]
